SporFonyBundle\Entity\Lesson:
    type: entity
    table: null
    repositoryClass: SporFonyBundle\Repository\LessonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        recurrence:
            type: string
            length: 255
            nullable: true
        date:
            type: date
    manyToOne:
        coach:
            targetEntity: User
            inversedBy: lessons
            joinColumn:
                name: coachId
                referencedColumnName: id
        room:
            targetEntity: Room
            inversedBy: lessons
            joinColumn:
                name: roomId
                referencedColumnName: id
        slot:
            targetEntity: Slot
            inversedBy: lessons
            joinColumn:
                name: slotId
                referencedColumnName: id
    uniqueConstraints:
        date_slot:
            columns: [date, slotId]
    lifecycleCallbacks: {  }
