SporFonyBundle\Entity\Room:
    type: entity
    table: null
    repositoryClass: SporFonyBundle\Repository\RoomRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        capacity:
            type: integer
    lifecycleCallbacks: {  }
