<?php

namespace SporFonyBundle\Repository;
use SporFonyBundle\Entity\Room;
use SporFonyBundle\Entity\Slot;

/**
 * ClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySlotAndRoom(Slot $slot, Room $room, \DateTime $date) {
        return $this->getEntityManager()
        -$this->findBy(['room' => $room, 'slot' => $slot, 'date' => $date]);
    }
}
