spor_fony:
    resource: "@SporFonyBundle/Resources/config/routing.yml"
    prefix:   /

spor_fony_logout:
    path: /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_reset:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_pass:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

