# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        main:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            pattern: ^/
            logout: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: logout
                target: login
            remember_me:
                secret: %secret%
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    encoders:
        SporFonyBundle\Entity\User: sha256

    role_hierarchy:
            ROLE_STUDENT:      ROLE_USER
            ROLE_TEACHER:     [ROLE_USER, ROLE_TEACHER]
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_TEACHER]

    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: ROLE_USER }
            - { path: ^/(lesson|room|slot|user)*/(new|edit|delete), roles: ROLE_TEACHER }
